CREATE DATABASE STUDENT
USE STUDENT
CREATE TABLE DEPARTMENTS(DNO CHAR(20) PRIMARY KEY, BUDGET BIGINT);
CREATE TABLE EMPLOYEES(SSN CHAR(20) PRIMARY KEY, SALARY BIGINT , PHONE CHAR(11),DNO CHAR(20)  FOREIGN KEY REFERENCES DEPARTMENTS(DNO), IS_EMPLOYEES TINYINT);
CREATE TABLE CHILDREN_OF_EMPLOYEES(NAME NVARCHAR(30) PRIMARY KEY, AGE INT,SSN CHAR(20) FOREIGN KEY REFERENCES EMPLOYEES(SSN));

ALTER TABLE DEPARTMENTS ADD DNAME NVARCHAR(20) ;

INSERT INTO DEPARTMENTS VALUES('A1',100000,N'BAN ĂN UỐNG');
INSERT INTO DEPARTMENTS VALUES('A2',100000,N'BAN HỌC TẬP');
INSERT INTO DEPARTMENTS VALUES('A3',300000,N'BAN VUI CHƠI');

INSERT INTO EMPLOYEES VALUES('E1',5000000,'0123456789','A1',0)
INSERT INTO EMPLOYEES VALUES('E2',7000000,'0123456788','A2',0)
INSERT INTO EMPLOYEES VALUES('E3',4500000,'0123456784','A3',1)

INSERT INTO CHILDREN_OF_EMPLOYEES VALUES(N'TRẦN VĂN A',7,'E1')
INSERT INTO CHILDREN_OF_EMPLOYEES VALUES(N'TRẦN VĂN B',5,'E2')
INSERT INTO CHILDREN_OF_EMPLOYEES VALUES(N'NGUYỄN THỊ C',6,'E3')

SELECT SSN,SALARY,PHONE,DNO FROM EMPLOYEES;
SELECT DNO, DNAME,BUDGET FROM DEPARTMENTS;

SELECT NAME,AGE FROM CHILDREN_OF_EMPLOYEES INNER JOIN EMPLOYEES ON CHILDREN_OF_EMPLOYEES.SSN = EMPLOYEES.SSN AND EMPLOYEES.IS_EMPLOYEES=1;



