USE STUDENT
CREATE TABLE STUDENT(SSN CHAR(20)NOT NULL PRIMARY KEY, NAME NVARCHAR(30),MAJOR NVARCHAR(20),BDATE DATE );
CREATE TABLE COURSE (COURSE CHAR(20) PRIMARY KEY,CNAME NVARCHAR(320),DEPT NVARCHAR(20));
CREATE TABLE ENROLL (
                 SSN CHAR(20),
				 COURSE CHAR(20) ,
				 QUARTER CHAR(20),
				 GRADE CHAR(20),
				 PRIMARY KEY (SSN,COURSE),
				 FOREIGN KEY (SSN) REFERENCES STUDENT(SSN),
				 FOREIGN KEY (COURSE) REFERENCES COURSE(COURSE),
				 
				 );
CREATE TABLE TEXT(
                           BOOK_ISBN CHAR(20),
                           BOOK_TITLE NVARCHAR(20),
						   PUBLISHER NVARCHAR(20),
						   AUTHOR NVARCHAR(20),
						   PRIMARY KEY(BOOK_ISBN),
                           );
CREATE TABLE BOOK_ADOPTION(
                           COURSE CHAR(20),
						   QUARTER CHAR(20),
						   BOOK_ISBN CHAR(20),
						   PRIMARY KEY(COURSE,BOOK_ISBN),
						   FOREIGN KEY (COURSE) REFERENCES COURSE(COURSE),
						   FOREIGN KEY (BOOK_ISBN ) REFERENCES TEXT(BOOK_ISBN ),
                           );
